// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ydjhsvawbpdjqppabzcm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlkamhzdmF3YnBkanFwcGFiemNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA0ODU1NjIsImV4cCI6MjA4NjA2MTU2Mn0.Sdgh-i2CBDmI11KtcwGpQqvPQl-psk1lJpsbBOpGKTU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
